//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receita
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Receita()
        {
            this.CompraRemedios = new HashSet<CompraRemedios>();
        }
    
        public int Id { get; set; }
        public string Data { get; set; }
        public string ClinicaHospital { get; set; }
        public int RemedioId { get; set; }
        public int MedicoId { get; set; }
        public int DoençaId { get; set; }
    
        public virtual Remedio Remedio { get; set; }
        public virtual Medico Medico { get; set; }
        public virtual Doença Doença { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompraRemedios> CompraRemedios { get; set; }
    }
}
