//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL5
{
    using System;
    
    public enum Tarja : int
    {
        Vermelha = 0,
        Amarela = 1,
        SemTarja = 2,
        Preta = 3
    }
}
